[package]
name = "scheming-sun"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
sc-frontend = {path="lib/sc-frontend"}
sc-input-data = {path="lib/sc-input-data"}
